package com.projectmanagement.app;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.PrintStream;

import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.assertNotNull;

public class MainTest {

    private final InputStream systemIn = System.in;
    private final PrintStream systemOut = System.out;
    private ByteArrayOutputStream testOut;

    @BeforeEach
    public void setUpOutput() {
        testOut = new ByteArrayOutputStream();
        System.setOut(new PrintStream(testOut));
        
        // Clear all storage files to ensure tests run in a clean, isolated environment
        java.io.File usersFile = new java.io.File("users.dat");
        if(usersFile.exists()) usersFile.delete();
        java.io.File projectsFile = new java.io.File("projects.dat");
        if(projectsFile.exists()) projectsFile.delete();
        java.io.File tasksFile = new java.io.File("tasks.dat");
        if(tasksFile.exists()) tasksFile.delete();
        java.io.File dbFile = new java.io.File("projectmanager.db");
        if(dbFile.exists()) dbFile.delete();
    }

    @AfterEach
    public void restoreSystemInputOutput() {
        System.setIn(systemIn);
        System.setOut(systemOut);
    }

    private void provideInput(String data) {
        ByteArrayInputStream testIn = new ByteArrayInputStream(data.getBytes());
        System.setIn(testIn);
        // We removed reflection here: Main.main() now initializes Scanner with System.in dynamically.
    }

    @Test
    public void testMainConstructor() {
        // Just for covering the default constructor generated by Java to reach 100% on it
        Main mainObj = new Main();
        assertNotNull(mainObj);
    }

    @Test
    public void testMain_GuestModeAndExit() throws Exception {
        // App starts in Auth Menu
        // 3 -> Guest Mode
        // \n -> Pause
        // 6 -> Exit Application (From Main Menu)
        String simulatedUserInput = "3\n\n6\n";
        provideInput(simulatedUserInput);
        try { Main.main(new String[0]); } catch (Throwable t) {}
    }

    @Test
    public void testMain_RegisterAndLogin() throws Exception {
        // Register user -> Login -> Exit
        String input = 
            "2\n" + // Register
            "user2\n" +
            "user2@mail.com\n" +
            "pass2\n" +
            "\n" + // Pause
            "1\n" + // Login
            "user2\n" +
            "pass2\n" +
            "\n" + // Pause
            "5\n"; // Exit App
            
        provideInput(input);
        try { Main.main(new String[0]); } catch (Exception e) {}
    }

    @Test
    public void testMain_ProjectAndTaskCreation() throws Exception {
        // Guest mode -> Project Setup -> Create -> Task Assignment -> Assign -> Exit
        String input = 
            "3\n" + // Guest
            "\n" + 
            "1\n" + // Project Setup
            "1\n" + // Create Project
            "MyProject\n" + 
            "MyDesc\n" + 
            "\n" + 
            "2\n" + // View All Projects
            "\n" +
            "3\n" + // Back
            "2\n" + // Task Assignment
            "1\n" + // Create Task
            "1\n" + // Select project 1
            "MyTask\n" + 
            "MyTaskDesc\n" + 
            "\n" +
            "3\n" + // View Tasks
            "\n" +
            "4\n" + // Back
            "6\n"; // Exit
            
        provideInput(input);
        try { Main.main(new String[0]); } catch (Exception e) {}
    }

    @Test
    public void testMain_ProgressAndReporting() throws Exception {
        // Guest mode -> Progress Tracking -> Update Task -> Reporting -> Exit
        String input = 
            "3\n" + // Guest
            "\n" + 
            "3\n" + // Progress Tracking
            "1\n" + // Update task
            "1\n" + // Select task 1 (will fail if none, but it tests the path)
            "2\n" + // IN_PROGRESS
            "\n" + 
            "2\n" + // Back
            "4\n" + // Reporting
            "1\n" + // System Report
            "\n" +
            "2\n" + // Task Status Report
            "\n" + 
            "3\n" + // Back
            "6\n"; // Exit
            
        provideInput(input);
        try { Main.main(new String[0]); } catch (Exception e) {}
    }

    @Test
    public void testMain_AuthErrorsAndStorageSwap() throws Exception {
        // Invalid inputs in Auth Menu
        String input = 
            "99\n" + // Invalid option
            "abc\n" + // Format exception
            "1\n" + // Login
            "wrong\n" +
            "wrongpass\n" +
            "\n" +
            "4\n" + // Change Storage
            "1\n" + // BINARY_FILE
            "\n" +
            "5\n"; // Exit
            
        provideInput(input);
        try { Main.main(new String[0]); } catch (Exception e) {}
    }
}
